// Package queryapiskeletonc
// ode is a copy-paste reference for the Postgres
// queries and pgxpool calls this project keeps reaching for. Nothing here is
// wired into the running API — it lives outside the go_be_skeleton module and
// is never built by it.
//
// Every handler below assumes this table:
//
//	CREATE TABLE users (
//	    id        SERIAL PRIMARY KEY,
//	    email     TEXT NOT NULL UNIQUE,   -- the upserts conflict on this
//	    name      TEXT NOT NULL,
//	    age       INT  NOT NULL,
//	    weight    DOUBLE PRECISION NOT NULL,
//	    gender    TEXT NOT NULL,
//	    height_cm DOUBLE PRECISION NOT NULL
//	);
//
// Which pgxpool call to reach for:
//
//	Exec      → writes you only need a row count from (UPDATE, DELETE)
//	QueryRow  → exactly one row back; pgx.ErrNoRows when there is none
//	Query     → zero-to-many rows back, including writes with RETURNING
//
// A single SQL statement is atomic on its own — Postgres wraps it in an
// implicit transaction — so none of these need db.Begin. Reach for an explicit
// transaction only once a handler issues two statements that must both land.
package queryapiskeletoncode

import (
	"encoding/json"
	"errors"
	"log/slog"
	"net/http"
	"strconv"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

type User struct {
	ID       int     `json:"id"`
	Email    string  `json:"email"`
	Name     string  `json:"name"`
	Age      int     `json:"age"`
	Weight   float64 `json:"weight"`
	Gender   string  `json:"gender"`
	HeightCm float64 `json:"height_cm"`
}

type UserHandler struct {
	DB *pgxpool.Pool
}

// userCols is the column order every query and scan in this file agrees on.
// Scans are positional, so a SELECT list and its Scan must not drift apart.
const userCols = `id, email, name, age, weight, gender, height_cm`

// scanUser reads one row in userCols order. pgx.Rows satisfies pgx.Row, so this
// works both for a QueryRow result and for a row inside a Query loop.
func scanUser(row pgx.Row, u *User) error {
	return row.Scan(&u.ID, &u.Email, &u.Name, &u.Age, &u.Weight, &u.Gender, &u.HeightCm)
}

// writeJSON sets the header, then the status, then the body — in that order.
// Header().Set after WriteHeader is silently ignored, and the first Write
// implies WriteHeader(200), so an early Encode locks in the wrong status.
func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if v != nil {
		_ = json.NewEncoder(w).Encode(v)
	}
}

// isUniqueViolation reports whether err is Postgres 23505 — a UNIQUE constraint
// rejection. Worth special-casing: it is the caller's fault (409), not a 500.
func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505"
}

// columns lifts one field out of every user, so the bulk statements below can
// pass one array per column instead of building $1..$60 by hand.
func columns(users []User) (emails, names, genders []string, ages []int64, weights, heights []float64) {
	emails = make([]string, len(users))
	names = make([]string, len(users))
	genders = make([]string, len(users))
	ages = make([]int64, len(users))
	weights = make([]float64, len(users))
	heights = make([]float64, len(users))
	for i, u := range users {
		emails[i] = u.Email
		names[i] = u.Name
		genders[i] = u.Gender
		ages[i] = int64(u.Age)
		weights[i] = u.Weight
		heights[i] = u.HeightCm
	}
	return
}

// collectUsers drains rows into a slice.
//
// The rows.Err() check is the important part: pgx reports most server-side
// failures from Next/Err rather than from Query, so a constraint violation on a
// RETURNING write is silently swallowed without it.
func collectUsers(rows pgx.Rows, capHint int) ([]User, error) {
	defer rows.Close()

	out := make([]User, 0, capHint)
	for rows.Next() {
		var u User
		if err := scanUser(rows, &u); err != nil {
			return nil, err
		}
		out = append(out, u)
	}
	return out, rows.Err()
}

// ---------------------------------------------------------------------------
// CREATE
// ---------------------------------------------------------------------------

// AddOne inserts a single user and returns the stored row.
//
// RETURNING is what makes this a QueryRow rather than an Exec — the id is
// generated by the SERIAL default, so it only exists after the insert runs.
//
//	POST /users
//	{"email":"a@b.c","name":"Ada","age":30,"weight":62.5,"gender":"Female","height_cm":170}
func (h *UserHandler) AddOne(w http.ResponseWriter, r *http.Request) {
	var u User
	if err := json.NewDecoder(r.Body).Decode(&u); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	const query = `
		INSERT INTO users (email, name, age, weight, gender, height_cm)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING ` + userCols

	row := h.DB.QueryRow(r.Context(), query, u.Email, u.Name, u.Age, u.Weight, u.Gender, u.HeightCm)
	if err := scanUser(row, &u); err != nil {
		if isUniqueViolation(err) {
			http.Error(w, "A user with that email already exists", http.StatusConflict)
			return
		}
		slog.Error("users: insert", "error", err)
		http.Error(w, "Failed to insert user", http.StatusInternalServerError)
		return
	}

	writeJSON(w, http.StatusCreated, u)
}

// AddAll inserts a whole JSON array of users in ONE statement.
//
// unnest turns the six array parameters into rows, which keeps the batch size a
// runtime detail instead of something baked into the SQL. Because it is a
// single statement it is all-or-nothing: one bad row rolls back the rest, with
// no transaction needed.
//
// The ::casts are explicit because the parameters arrive as bigint[] and
// double precision[]; Postgres assignment-casts them into the int and
// double precision columns.
//
//	POST /users/bulk
//	[{"email":"a@b.c", ...}, {"email":"d@e.f", ...}]
func (h *UserHandler) AddAll(w http.ResponseWriter, r *http.Request) {
	var users []User
	if err := json.NewDecoder(r.Body).Decode(&users); err != nil {
		http.Error(w, "Invalid request body — expected a JSON array", http.StatusBadRequest)
		return
	}
	if len(users) == 0 {
		writeJSON(w, http.StatusOK, []User{})
		return
	}

	const query = `
		INSERT INTO users (email, name, age, weight, gender, height_cm)
		SELECT * FROM unnest(
			$1::text[],
			$2::text[],
			$3::bigint[],
			$4::double precision[],
			$5::text[],
			$6::double precision[]
		)
		RETURNING ` + userCols

	emails, names, genders, ages, weights, heights := columns(users)

	rows, err := h.DB.Query(r.Context(), query, emails, names, ages, weights, genders, heights)
	if err != nil {
		slog.Error("users: bulk insert", "error", err)
		http.Error(w, "Failed to insert users", http.StatusInternalServerError)
		return
	}

	stored, err := collectUsers(rows, len(users))
	if err != nil {
		if isUniqueViolation(err) {
			http.Error(w, "One of those emails already exists", http.StatusConflict)
			return
		}
		slog.Error("users: bulk insert", "error", err)
		http.Error(w, "Failed to insert users", http.StatusInternalServerError)
		return
	}

	writeJSON(w, http.StatusCreated, stored)
}

// ---------------------------------------------------------------------------
// READ
// ---------------------------------------------------------------------------

// GetAll returns every user.
//
// ORDER BY is not decoration — without it Postgres may return rows in any
// order, and that order can change between identical calls. Add LIMIT/OFFSET
// (see the notes at the bottom) before this table gets big.
func (h *UserHandler) GetAll(w http.ResponseWriter, r *http.Request) {
	const query = `SELECT ` + userCols + ` FROM users ORDER BY id`

	rows, err := h.DB.Query(r.Context(), query)
	if err != nil {
		slog.Error("users: select all", "error", err)
		http.Error(w, "Database error", http.StatusInternalServerError)
		return
	}

	users, err := collectUsers(rows, 0)
	if err != nil {
		slog.Error("users: select all", "error", err)
		http.Error(w, "Database error", http.StatusInternalServerError)
		return
	}

	// An empty result must encode as [] and not null, which is why collectUsers
	// returns a made slice rather than a nil one.
	writeJSON(w, http.StatusOK, users)
}

// GetOne returns a single user by path id.
//
//	GET /users/{id}
func (h *UserHandler) GetOne(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id")) // Go 1.22+ path patterns
	if err != nil {
		http.Error(w, "Invalid user ID", http.StatusBadRequest)
		return
	}

	const query = `SELECT ` + userCols + ` FROM users WHERE id = $1`

	var u User
	if err := scanUser(h.DB.QueryRow(r.Context(), query, id), &u); err != nil {
		// QueryRow folds "no rows" into a Scan error, so this is where a 404
		// gets told apart from a real failure.
		if errors.Is(err, pgx.ErrNoRows) {
			http.Error(w, "User not found", http.StatusNotFound)
			return
		}
		slog.Error("users: select one", "error", err, "id", id)
		http.Error(w, "Database error", http.StatusInternalServerError)
		return
	}

	writeJSON(w, http.StatusOK, u)
}

// ---------------------------------------------------------------------------
// UPSERT
// ---------------------------------------------------------------------------

// UpsertOne inserts a user, or updates the existing row with that email.
//
// ON CONFLICT needs a real UNIQUE constraint on the named column or Postgres
// errors out. EXCLUDED is the row that was proposed for insertion; note that id
// and email are deliberately not overwritten from it.
func (h *UserHandler) UpsertOne(w http.ResponseWriter, r *http.Request) {
	var u User
	if err := json.NewDecoder(r.Body).Decode(&u); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	const query = `
		INSERT INTO users (email, name, age, weight, gender, height_cm)
		VALUES ($1, $2, $3, $4, $5, $6)
		ON CONFLICT (email) DO UPDATE
		SET name      = EXCLUDED.name,
		    age       = EXCLUDED.age,
		    weight    = EXCLUDED.weight,
		    gender    = EXCLUDED.gender,
		    height_cm = EXCLUDED.height_cm
		RETURNING ` + userCols

	row := h.DB.QueryRow(r.Context(), query, u.Email, u.Name, u.Age, u.Weight, u.Gender, u.HeightCm)
	if err := scanUser(row, &u); err != nil {
		slog.Error("users: upsert", "error", err)
		http.Error(w, "Failed to save user", http.StatusInternalServerError)
		return
	}

	writeJSON(w, http.StatusOK, u)
}

// UpsertAll is the bulk form: seed-or-refresh a whole list in one statement.
// This is the shape to reach for when populating reference data on boot.
//
// One sharp edge: if the same email appears twice in the batch, Postgres fails
// with "ON CONFLICT DO UPDATE command cannot affect row a second time". Dedupe
// in Go first, or wrap the source in SELECT DISTINCT ON (email).
func (h *UserHandler) UpsertAll(w http.ResponseWriter, r *http.Request) {
	var users []User
	if err := json.NewDecoder(r.Body).Decode(&users); err != nil {
		http.Error(w, "Invalid request body — expected a JSON array", http.StatusBadRequest)
		return
	}
	if len(users) == 0 {
		writeJSON(w, http.StatusOK, []User{})
		return
	}

	const query = `
		INSERT INTO users (email, name, age, weight, gender, height_cm)
		SELECT * FROM unnest(
			$1::text[],
			$2::text[],
			$3::bigint[],
			$4::double precision[],
			$5::text[],
			$6::double precision[]
		)
		ON CONFLICT (email) DO UPDATE
		SET name      = EXCLUDED.name,
		    age       = EXCLUDED.age,
		    weight    = EXCLUDED.weight,
		    gender    = EXCLUDED.gender,
		    height_cm = EXCLUDED.height_cm
		RETURNING ` + userCols

	emails, names, genders, ages, weights, heights := columns(users)

	rows, err := h.DB.Query(r.Context(), query, emails, names, ages, weights, genders, heights)
	if err != nil {
		slog.Error("users: bulk upsert", "error", err)
		http.Error(w, "Failed to save users", http.StatusInternalServerError)
		return
	}

	stored, err := collectUsers(rows, len(users))
	if err != nil {
		slog.Error("users: bulk upsert", "error", err)
		http.Error(w, "Failed to save users", http.StatusInternalServerError)
		return
	}

	writeJSON(w, http.StatusOK, stored)
}

// ---------------------------------------------------------------------------
// UPDATE
// ---------------------------------------------------------------------------

// EditOne replaces every field of one user.
//
// RETURNING plus pgx.ErrNoRows distinguishes "no such id" from success in a
// single round trip. The Exec alternative is fine too — it just reports the
// same thing through a row count instead:
//
//	tag, err := h.DB.Exec(ctx, query, ...)
//	if tag.RowsAffected() == 0 { /* 404 */ }
//
//	PUT /users/{id}
func (h *UserHandler) EditOne(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid user ID", http.StatusBadRequest)
		return
	}

	var u User
	if err := json.NewDecoder(r.Body).Decode(&u); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	const query = `
		UPDATE users
		SET email     = $1,
		    name      = $2,
		    age       = $3,
		    weight    = $4,
		    gender    = $5,
		    height_cm = $6
		WHERE id = $7
		RETURNING ` + userCols

	row := h.DB.QueryRow(r.Context(), query, u.Email, u.Name, u.Age, u.Weight, u.Gender, u.HeightCm, id)
	if err := scanUser(row, &u); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			http.Error(w, "User not found", http.StatusNotFound)
			return
		}
		if isUniqueViolation(err) {
			http.Error(w, "A user with that email already exists", http.StatusConflict)
			return
		}
		slog.Error("users: update one", "error", err, "id", id)
		http.Error(w, "Failed to update user", http.StatusInternalServerError)
		return
	}

	writeJSON(w, http.StatusOK, u)
}

// EditMany updates a list of users, each with its own values, in ONE statement.
//
// The trick is UPDATE ... FROM unnest(...) AS v(...): unnest builds a virtual
// table of new values and the WHERE joins it to the real one on id. The naive
// alternative — a Go loop issuing one UPDATE per user — costs a round trip each
// and needs an explicit transaction to stay atomic.
//
// Ids not present in the table simply match nothing; compare len(stored) with
// len(users) to detect that.
//
//	PATCH /users/bulk
//	[{"id":1,"email":"a@b.c", ...}, {"id":2, ...}]
func (h *UserHandler) EditMany(w http.ResponseWriter, r *http.Request) {
	var users []User
	if err := json.NewDecoder(r.Body).Decode(&users); err != nil {
		http.Error(w, "Invalid request body — expected a JSON array", http.StatusBadRequest)
		return
	}
	if len(users) == 0 {
		writeJSON(w, http.StatusOK, []User{})
		return
	}

	const query = `
		UPDATE users AS u
		SET email     = v.email,
		    name      = v.name,
		    age       = v.age,
		    weight    = v.weight,
		    gender    = v.gender,
		    height_cm = v.height_cm
		FROM unnest(
			$1::bigint[],
			$2::text[],
			$3::text[],
			$4::bigint[],
			$5::double precision[],
			$6::text[],
			$7::double precision[]
		) AS v(id, email, name, age, weight, gender, height_cm)
		WHERE u.id = v.id
		RETURNING u.id, u.email, u.name, u.age, u.weight, u.gender, u.height_cm`

	ids := make([]int64, len(users))
	for i, u := range users {
		ids[i] = int64(u.ID)
	}
	emails, names, genders, ages, weights, heights := columns(users)

	rows, err := h.DB.Query(r.Context(), query, ids, emails, names, ages, weights, genders, heights)
	if err != nil {
		slog.Error("users: update many", "error", err)
		http.Error(w, "Failed to update users", http.StatusInternalServerError)
		return
	}

	stored, err := collectUsers(rows, len(users))
	if err != nil {
		slog.Error("users: update many", "error", err)
		http.Error(w, "Failed to update users", http.StatusInternalServerError)
		return
	}

	writeJSON(w, http.StatusOK, stored)
}

// ---------------------------------------------------------------------------
// DELETE
// ---------------------------------------------------------------------------

// DeleteOne removes one user by id.
//
// Nothing comes back, so this is an Exec: the row count is the only signal, and
// zero means the id never existed.
//
//	DELETE /users/{id}
func (h *UserHandler) DeleteOne(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.Error(w, "Invalid user ID", http.StatusBadRequest)
		return
	}

	const query = `DELETE FROM users WHERE id = $1`

	tag, err := h.DB.Exec(r.Context(), query, id)
	if err != nil {
		slog.Error("users: delete one", "error", err, "id", id)
		http.Error(w, "Failed to delete user", http.StatusInternalServerError)
		return
	}
	if tag.RowsAffected() == 0 {
		http.Error(w, "User not found", http.StatusNotFound)
		return
	}

	// 204 says "done, nothing to send" — do not also write a body.
	w.WriteHeader(http.StatusNoContent)
}

// DeleteAll empties the table.
//
// Destructive and trivially reachable, so it demands a deliberate ?confirm=true
// rather than firing on a stray request. Ship it behind auth or not at all.
//
// DELETE is the right verb here: it fires triggers, respects foreign keys row
// by row, and can be rolled back cheaply. TRUNCATE users RESTART IDENTITY is
// far faster on a large table but takes an ACCESS EXCLUSIVE lock and fails
// outright if another table references this one.
//
//	DELETE /users?confirm=true
func (h *UserHandler) DeleteAll(w http.ResponseWriter, r *http.Request) {
	if r.URL.Query().Get("confirm") != "true" {
		http.Error(w, "Refusing to delete every user without ?confirm=true", http.StatusBadRequest)
		return
	}

	const query = `DELETE FROM users`

	tag, err := h.DB.Exec(r.Context(), query)
	if err != nil {
		slog.Error("users: delete all", "error", err)
		http.Error(w, "Failed to delete users", http.StatusInternalServerError)
		return
	}

	writeJSON(w, http.StatusOK, map[string]int64{"deleted": tag.RowsAffected()})
}

// ---------------------------------------------------------------------------
// Variants worth remembering
// ---------------------------------------------------------------------------
//
// Pagination — always paired with a stable ORDER BY:
//
//	SELECT id, email, name FROM users ORDER BY id LIMIT $1 OFFSET $2
//
// Same new value across many rows — much simpler than unnest when only the ids
// vary. = ANY($1::bigint[]) takes one array parameter instead of $1..$n:
//
//	UPDATE users SET gender = $1 WHERE id = ANY($2::bigint[])
//	DELETE FROM users WHERE id = ANY($1::bigint[])
//
// Count and existence — QueryRow always returns exactly one row here, so
// pgx.ErrNoRows is impossible and EXISTS beats COUNT(*) > 0 because it stops at
// the first match:
//
//	var n int
//	h.DB.QueryRow(ctx, `SELECT count(*) FROM users`).Scan(&n)
//
//	var exists bool
//	h.DB.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)`, email).Scan(&exists)
//
// Join across tables — prefix every column, and scan in exactly SELECT order:
//
//	SELECT u.id, u.name, s.bmi_value, s.bmr_value, s.verdict
//	FROM users u
//	JOIN user_specs s ON u.id = s.user_id
//	WHERE u.id = $1
//
// A LEFT JOIN puts NULLs in the right-hand columns when there is no match, so
// scan those into *float64 / sql.NullFloat64 rather than float64.
//
// Explicit transaction — for two or more statements that must land together,
// e.g. insert a user then their specs row using the returned id. Rollback after
// a successful Commit is a no-op, so deferring it unconditionally is the
// idiom:
//
//	tx, err := h.DB.Begin(ctx)
//	if err != nil { return err }
//	defer tx.Rollback(ctx)
//
//	var id int
//	if err := tx.QueryRow(ctx, insertUser, ...).Scan(&id); err != nil { return err }
//	if _, err := tx.Exec(ctx, insertSpecs, id, ...); err != nil { return err }
//
//	return tx.Commit(ctx)
//
// CopyFrom — the fastest bulk load by a wide margin, but it is a raw stream:
// no ON CONFLICT, no RETURNING. Good for seeding an empty table, useless for
// upserts:
//
//	_, err := h.DB.CopyFrom(ctx,
//	    pgx.Identifier{"users"},
//	    []string{"email", "name", "age", "weight", "gender", "height_cm"},
//	    pgx.CopyFromSlice(len(users), func(i int) ([]any, error) {
//	        u := users[i]
//	        return []any{u.Email, u.Name, u.Age, u.Weight, u.Gender, u.HeightCm}, nil
//	    }),
//	)
//
// pgx.Batch — many *different* statements in one round trip. Queue them inside
// a transaction if they must all land; a batch is not atomic by itself:
//
//	batch := &pgx.Batch{}
//	for _, u := range users {
//	    batch.Queue(`INSERT INTO users (...) VALUES ($1, ...)`, u.Email /* ... */)
//	}
//	results := h.DB.SendBatch(ctx, batch)
//	defer results.Close()
//
// pgx.CollectRows — replaces the manual scan loop. RowToStructByName matches on
// `db:"..."` struct tags (falling back to lowercased field names), so User would
// need db tags before this works:
//
//	rows, err := h.DB.Query(ctx, query)
//	if err != nil { return nil, err }
//	users, err := pgx.CollectRows(rows, pgx.RowToStructByName[User])
//
// Partial update — the SETs above overwrite every column, so a PATCH that omits
// a field would zero it. Either decode into a struct of pointers and build the
// SET list from the non-nil ones, or lean on COALESCE to keep the current value
// when a parameter arrives NULL:
//
//	UPDATE users SET name = COALESCE($1, name), age = COALESCE($2, age) WHERE id = $3
