// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: aidata.proto

package textpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request payload sent from Go -> Python
type AiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiRequest) Reset() {
	*x = AiRequest{}
	mi := &file_aidata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiRequest) ProtoMessage() {}

func (x *AiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aidata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiRequest.ProtoReflect.Descriptor instead.
func (*AiRequest) Descriptor() ([]byte, []int) {
	return file_aidata_proto_rawDescGZIP(), []int{0}
}

func (x *AiRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Response payload sent back from Python -> Go
type AiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiResponse) Reset() {
	*x = AiResponse{}
	mi := &file_aidata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiResponse) ProtoMessage() {}

func (x *AiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aidata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiResponse.ProtoReflect.Descriptor instead.
func (*AiResponse) Descriptor() ([]byte, []int) {
	return file_aidata_proto_rawDescGZIP(), []int{1}
}

func (x *AiResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_aidata_proto protoreflect.FileDescriptor

const file_aidata_proto_rawDesc = "" +
	"\n" +
	"\faidata.proto\x12\vtextservice\"\x1f\n" +
	"\tAiRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\" \n" +
	"\n" +
	"AiResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data2N\n" +
	"\fAiDatService\x12>\n" +
	"\vProcessText\x12\x16.textservice.AiRequest\x1a\x17.textservice.AiResponseB\n" +
	"Z\b./textpbb\x06proto3"

var (
	file_aidata_proto_rawDescOnce sync.Once
	file_aidata_proto_rawDescData []byte
)

func file_aidata_proto_rawDescGZIP() []byte {
	file_aidata_proto_rawDescOnce.Do(func() {
		file_aidata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aidata_proto_rawDesc), len(file_aidata_proto_rawDesc)))
	})
	return file_aidata_proto_rawDescData
}

var file_aidata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aidata_proto_goTypes = []any{
	(*AiRequest)(nil),  // 0: textservice.AiRequest
	(*AiResponse)(nil), // 1: textservice.AiResponse
}
var file_aidata_proto_depIdxs = []int32{
	0, // 0: textservice.AiDatService.ProcessText:input_type -> textservice.AiRequest
	1, // 1: textservice.AiDatService.ProcessText:output_type -> textservice.AiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aidata_proto_init() }
func file_aidata_proto_init() {
	if File_aidata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aidata_proto_rawDesc), len(file_aidata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aidata_proto_goTypes,
		DependencyIndexes: file_aidata_proto_depIdxs,
		MessageInfos:      file_aidata_proto_msgTypes,
	}.Build()
	File_aidata_proto = out.File
	file_aidata_proto_goTypes = nil
	file_aidata_proto_depIdxs = nil
}
