// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: textservice.proto

package textpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request payload sent from Go -> Python
type TextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_textservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_textservice_proto_rawDescGZIP(), []int{0}
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Response payload sent back from Python -> Go
type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_textservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_textservice_proto_rawDescGZIP(), []int{1}
}

func (x *TextResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_textservice_proto protoreflect.FileDescriptor

const file_textservice_proto_rawDesc = "" +
	"\n" +
	"\x11textservice.proto\x12\vtextservice\"!\n" +
	"\vTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"&\n" +
	"\fTextResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2Q\n" +
	"\vTextService\x12B\n" +
	"\vProcessText\x12\x18.textservice.TextRequest\x1a\x19.textservice.TextResponseB\n" +
	"Z\b./textpbb\x06proto3"

var (
	file_textservice_proto_rawDescOnce sync.Once
	file_textservice_proto_rawDescData []byte
)

func file_textservice_proto_rawDescGZIP() []byte {
	file_textservice_proto_rawDescOnce.Do(func() {
		file_textservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_textservice_proto_rawDesc), len(file_textservice_proto_rawDesc)))
	})
	return file_textservice_proto_rawDescData
}

var file_textservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_textservice_proto_goTypes = []any{
	(*TextRequest)(nil),  // 0: textservice.TextRequest
	(*TextResponse)(nil), // 1: textservice.TextResponse
}
var file_textservice_proto_depIdxs = []int32{
	0, // 0: textservice.TextService.ProcessText:input_type -> textservice.TextRequest
	1, // 1: textservice.TextService.ProcessText:output_type -> textservice.TextResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_textservice_proto_init() }
func file_textservice_proto_init() {
	if File_textservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_textservice_proto_rawDesc), len(file_textservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_textservice_proto_goTypes,
		DependencyIndexes: file_textservice_proto_depIdxs,
		MessageInfos:      file_textservice_proto_msgTypes,
	}.Build()
	File_textservice_proto = out.File
	file_textservice_proto_goTypes = nil
	file_textservice_proto_depIdxs = nil
}
